spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/BaseOfPeople
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
  flyway:
    enabled: true
    validate-on-migrate: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher