CREATE TABLE users
(
    user_id      int4 GENERATED BY DEFAULT AS IDENTITY,
    e_mail       VARCHAR(255),
    first_name   VARCHAR(255),
    last_name    VARCHAR(255),
    second_name  VARCHAR(255),
    phone_number int8,
    role         VARCHAR(255),
    login        VARCHAR(255),
    password     VARCHAR(255),
    PRIMARY KEY (user_id)
);
